/* ============================================================
   Shared standard asset code reference (1997 & 1998 registers).
   Loaded by both the Asset Manager dashboard (index.html) and the
   Location Records page (locations.html) so the asset code lookup is
   available in both places from a single source of truth.
   ============================================================ */
        window.ASSET_CODES_1998 = [
            {code: "1467", desc: "Analyser, Acid Base"},
            {code: "0000", desc: "Analyser, Electrolite"},
            {code: "1341", desc: "Apparatus, Suction-pipeline Vacuum Sgl Jar"},
            {code: "1342", desc: "Apparatus, Suction-pipeline Wall Mounted Sgl Jar"},
            {code: "694", desc: "Apron, Lead"},
            {code: "1343", desc: "Aspirator - Low Volume, Drainage Mobile"},
            {code: "1344", desc: "Bag, Baby Resuscitation"},
            {code: "1345", desc: "Bag, Paediatric Resuscitation"},
            {code: "456", desc: "Balance, Analytical Measuring"},
            {code: "000", desc: "Balance, Electronic"},
            {code: "000", desc: "Balance, Topload"},
            {code: "1455", desc: "Ball, Medicine"},
            {code: "1479", desc: "Bars, Grab"},
            {code: "1457", desc: "Bars, Wall"},
            {code: "1456", desc: "Bars, Parallel"},
            {code: "1351", desc: "Bassinet, designer with Cover"},
            {code: "247", desc: "Bath, Infant-Mobile"},
            {code: "1475", desc: "Beam, balance"},
            {code: "109", desc: "Bed, Folding"},
            {code: "1476", desc: "Bed, Lumbar Traction"},
            {code: "1477", desc: "Bed, Mobilization"},
            {code: "1478", desc: "Bed, Neuro CVA"},
            {code: "1482", desc: "Bed, Wooden"},
            {code: "1480", desc: "Bell, Dumb"},
            {code: "1481", desc: "Bench, Quad"},
            {code: "250", desc: "Bench - Seat, 2 Person"},
            {code: "251", desc: "Bench - Seat, 4 Person"},
            {code: "627", desc: "Billirubinometer"},
            {code: "585", desc: "Bin, Storage - X-ray Film"},
            {code: "586", desc: "Bin, Waste - X-ray Film"},
            {code: "101", desc: "Bin, Storage - Ingredients"},
            {code: "102", desc: "Bin, Disposal - Food Mobile"},
            {code: "1350", desc: "Bin Used Items - CSSD"},
            {code: "103", desc: "Bin, Paper Towel - Wall Mounted"},
            {code: "108", desc: "Bin, Paper Towel - Floor/Wall"},
            {code: "441", desc: "Binder, Electric"},
            {code: "587", desc: "Blender, Barium"},
            {code: "1352", desc: "Block, Butcher's"},
            {code: "1483", desc: "Board, Balance"},
            {code: "1000", desc: "Board, Flip Chart"},
            {code: "370", desc: "Boiler, Hot Water - 45 Litre Bench Mounted"},
            {code: "1348", desc: "Bottle Urine - Polyprophylene"},
            {code: "1484", desc: "Bowl, Emesis"},
            {code: "458", desc: "Box, Typing R.H."},
            {code: "683", desc: "Bucky, Wall - Vertical Angulating Sgl Plane"},
            {code: "1349", desc: "Bucket, Kick About"},
            {code: "455", desc: "Cabinet, Biological"},
            {code: "000", desc: "Cables, Electrode"},
            {code: "459", desc: "Camera, Auto"},
            {code: "393", desc: "Camera, Video"},
            {code: "1360", desc: "Cabinet, Heated Lotions - Bench Mounted"},
            {code: "1361", desc: "Cabinet, Storage - Flammable"},
            {code: "729", desc: "Cabinet, Sterilizer with Printer (Vacuum)"},
            {code: "482", desc: "Care Centre, Intensive - Infant"},
            {code: "374", desc: "Cart, Beverage"},
            {code: "1363", desc: "Cart, Cast"},
            {code: "349", desc: "Cart, Gourmet"},
            {code: "361", desc: "Cart, Food Delivery"},
            {code: "364", desc: "Cart, Ice"},
            {code: "1364", desc: "Cart, Utility - 3 Shelves"},
            {code: "242", desc: "Chair, Blood Drawing"},
            {code: "249", desc: "Chair, Child"},
            {code: "248", desc: "Chair, Rocking"},
            {code: "1485", desc: "Chair, Shortwave Diathermy"},
            {code: "144", desc: "Chair, Wheel - Adult w/I.V Pole"},
            {code: "154", desc: "Chair, Wheel - Child - Folding"},
            {code: "1486", desc: "Chair, Whirlpool Treatment"},
            {code: "1353", desc: "Cleanser, Ultrasonic"},
            {code: "1487", desc: "Club, Exercise"},
            {code: "405", desc: "Computer"},
            {code: "440", desc: "Computer, Laptop"},
            {code: "1468", desc: "Connector, Camera OTV"},
            {code: "158", desc: "Console, Patient Service"},
            {code: "366", desc: "Cooler, Food"},
            {code: "1365", desc: "Container, Mortuary Waste - Portable"},
            {code: "444", desc: "Concentrator, Oxygen"},
            {code: "1488", desc: "Couch, Massage Treatment"},
            {code: "1356", desc: "Counter, Infusion - Flow Rate"},
            {code: "243", desc: "Credenza"},
            {code: "1358", desc: "Crib, Resuscitation"},
            {code: "1357", desc: "Crovpette, Oxygen"},
            {code: "1354", desc: "Crutch, Axilla - Adult Adjustable"},
            {code: "1355", desc: "Crutch, Axilla - Child Adjustable"},
            {code: "246", desc: "Cubicle, Curtain Track"},
            {code: "1369", desc: "Cupboard, Drugs - Wall Mounted, Lockable"},
            {code: "1362", desc: "Cupboard, Urine Test - Wall Mounted"},
            {code: "229", desc: "Cushion"},
            {code: "997", desc: "Cylinder, Carbon Dioxide"},
            {code: "1366", desc: "Cylinder, Oxygen Flowmeter - w/Regulator"},
            {code: "1466", desc: "Datascope, Passport"},
            {code: "1404", desc: "Dispenser, Nail Brush"},
            {code: "358", desc: "Dispenser, Paper"},
            {code: "449", desc: "Dispenser, Pharmacy Label"},
            {code: "1405", desc: "Dispenser, Scrub Solution"},
            {code: "357", desc: "Dispenser, Soap"},
            {code: "1368", desc: "Dispenser, Sterile Pack"},
            {code: "1367", desc: "Dispenser, Syringe"},
            {code: "178", desc: "Drawer, Pedestal"},
            {code: "1469", desc: "Dryer, Tube"},
            {code: "684", desc: "Electrocardiagraph, 3 Channel"},
            {code: "490", desc: "Emerald"},
            {code: "994", desc: "Epidiascope"},
            {code: "1369", desc: "Exerciser, Complete Jet"},
            {code: "1370", desc: "Exerciser, Chest Pulley - Mid Triplet weights"},
            {code: "1371", desc: "Exerciser, Finger Extension"},
            {code: "1372", desc: "Exerciser, Overhead Pulley - Wall Mounted"},
            {code: "1373", desc: "Exerciser, Shoulder, Abduction Ladder, Wall Mnt"},
            {code: "1374", desc: "Flowmeter, Oxygen"},
            {code: "1375", desc: "Flowmeter, Oxygen Pipeline - Sgl w/Humidifier"},
            {code: "1489", desc: "Footrest - Metal"},
            {code: "1490", desc: "Footrest, Shortwave Diathermy"},
            {code: "395", desc: "Freezer, Deep - Chest"},
            {code: "396", desc: "Freezer, Upright - 49 Cu. Ft. Double Door"},
            {code: "588", desc: "Gloves, Lead"},
            {code: "367", desc: "Griddle"},
            {code: "584", desc: "Hammer, Percussion"},
            {code: "255", desc: "Hamper, Trash"},
            {code: "261", desc: "Hamper, Linen-Round"},
            {code: "1491", desc: "Hand, Grip"},
            {code: "667", desc: "Hatch, Film"},
            {code: "1492", desc: "Holder, Sharps"},
            {code: "1376", desc: "Hoist, Patient - Mobile"},
            {code: "262", desc: "Holder, Sack - Free Standing"},
            {code: "483", desc: "Hood, Biological Container"},
            {code: "1377", desc: "Hood, Fume Extract"},
            {code: "1378", desc: "Hood, Laninar Flow - Counter Top Vertical"},
            {code: "863", desc: "Hose, Fire"},
            {code: "1379", desc: "Hose, Gas - Ceiling Drip"},
            {code: "397", desc: "Hotplate, Domestic - Double Burner"},
            {code: "442", desc: "Hub, Internet"},
            {code: "1380", desc: "Humidifier, Ventilator"},
            {code: "1459", desc: "Hydrocollator"},
            {code: "712", desc: "Illuminator, X-ray Film - Spot Darkroom Light"},
            {code: "709", desc: "Illuminator, X-ray - 2 Panel Surface Mount"},
            {code: "710", desc: "Illuminator, X-ray - 3 Panel Surface Mount"},
            {code: "711", desc: "Illuminator, X-ray - 4 Panel Surface Mount"},
            {code: "1381", desc: "Illuminator, X-ray - 6 Panel Surface Mount"},
            {code: "489", desc: "Incubator, Carbon Dioxide"},
            {code: "1382", desc: "Incubator, Neonate, Basic"},
            {code: "371", desc: "Insect Killer - Wall Mounted"},
            {code: "263", desc: "Insert, Serving Tray"},
            {code: "303", desc: "Kettle, Steam/Steamer"},
            {code: "446", desc: "Keyboard, Computer"},
            {code: "1493", desc: "Kneeboard"},
            {code: "1383", desc: "Lamp, Operating - Ceiling Mounted w/Satellite"},
            {code: "1384", desc: "Lamp, Operating - Mobile"},
            {code: "1510", desc: "Lamp, Physiotherapy"},
            {code: "359", desc: "Lifter, Dish"},
            {code: "1386", desc: "Light Examination - Mobile w/Cool Spot"},
            {code: "1385", desc: "Light Examination - Ceiling Mounted"},
            {code: "1387", desc: "Light Surgical - Minor Dual Head"},
            {code: "275", desc: "Locker, Clothes - Single"},
            {code: "451", desc: "Machine, Blood Gas"},
            {code: "668", desc: "Machine, ECG"},
            {code: "1148", desc: "Machine, Haematology"},
            {code: "991", desc: "Machine, Ice - Counter Top"},
            {code: "992", desc: "Machine, Ice - Cube, Floor Unit"},
            {code: "1143", desc: "Machine, Liquid Packaging"},
            {code: "1494", desc: "Machine, Mammogram"},
            {code: "1144", desc: "Machine, Sealing - Rotary Heat"},
            {code: "260", desc: "Machine, Surging"},
            {code: "1495", desc: "Machine, Traction"},
            {code: "1496", desc: "Machine, Transcutaneous"},
            {code: "1145", desc: "Machine, Tube Closing and Folding"},
            {code: "1391", desc: "Mat, Exercise"},
            {code: "1141", desc: "Mill, Ointment"},
            {code: "1142", desc: "Mixer, Ointment"},
            {code: "1149", desc: "Mixer, Vortex"},
            {code: "445", desc: "Modem, Computer"},
            {code: "719", desc: "Monitor, Blood Pressure - Auto Printer"},
            {code: "613", desc: "Monitor, Defibrillator"},
            {code: "1388", desc: "Monitor ECG - portable, Battery Operated"},
            {code: "1390", desc: "Monitor, Neonatal"},
            {code: "679", desc: "Monitor, Oxygen - Hi/Lo Alarm"},
            {code: "718", desc: "Monitor, Patient - Sgl Channel w/Wall Mount"},
            {code: "1389", desc: "Monitor, Patient - 2 Channel"},
            {code: "720", desc: "Monitor, Trace - Physiological ECG/2 Pressure"},
            {code: "1392", desc: "Nebulizer - W/Stand"},
            {code: "1150", desc: "Onyx"},
            {code: "372", desc: "Opener, Can - Wall Mounted"},
            {code: "1002", desc: "Opener, Tin"},
            {code: "1393", desc: "Otoscope/Ophthalmoscope - Battery Powered"},
            {code: "373", desc: "Oven, Convention"},
            {code: "1470", desc: "Pan, Scrub"},
            {code: "1511", desc: "Panel, X-ray Control"},
            {code: "1460", desc: "Pedals"},
            {code: "241", desc: "Painting, Wall"},
            {code: "1498", desc: "Podoscope"},
            {code: "245", desc: "Pot, Clay"},
            {code: "264", desc: "Potty Infant"},
            {code: "265", desc: "Press, General Utility"},
            {code: "1091", desc: "Printer, Copy"},
            {code: "516", desc: "Printer, Counter"},
            {code: "000", desc: "Processor, Film"},
            {code: "688", desc: "Processor, Film - Radiographic"},
            {code: "1499", desc: "Pulley"},
            {code: "1395", desc: "Pump, Infusion"},
            {code: "267", desc: "Rack, Bedpan"},
            {code: "268", desc: "Rack, Chart - 20 Capacity, Counter Top"},
            {code: "269", desc: "Rack, Chart - 40 Capacity, Counter Top"},
            {code: "1397", desc: "Rack, CSSD Paper - Mobile"},
            {code: "693", desc: "Rack, Glove - Multiple Apron"},
            {code: "237", desc: "Rack, Luggage"},
            {code: "276", desc: "Rack, Metal Pan - 4 tier, Mobile"},
            {code: "1151", desc: "Rack, Pippet"},
            {code: "266", desc: "Rack, Storage - Free Standing"},
            {code: "244", desc: "Rack, Wooden/Metal"},
            {code: "998", desc: "Radio, AM/FM"},
            {code: "252", desc: "Range, Open 4 Burner"},
            {code: "253", desc: "Range, Open 12 Burner"},
            {code: "993", desc: "Range, Stock Pot"},
            {code: "379", desc: "Receptacle, Trash"},
            {code: "378", desc: "Receptacle, Trash - Large, Mobile"},
            {code: "377", desc: "Refrigerator - 17.7 Cu ft."},
            {code: "1399", desc: "Refrigerator, Drug storage - Free Standing"},
            {code: "0000", desc: "Refrigerator, Morgue"},
            {code: "1398", desc: "Refrigerator, Morgue - 4 Compartment"},
            {code: "1401", desc: "Refrigerator, Morgue - 9 Compartment"},
            {code: "1400", desc: "Refrigerator, Pharmaceutical - Double Door"},
            {code: "386", desc: "Shelving, Wire"},
            {code: "714", desc: "Shelving, X-ray"},
            {code: "723", desc: "Sink, Clinical - Flushing Rim"},
            {code: "365", desc: "Sink, Commercial"},
            {code: "384", desc: "Sink, Pot Washing - 3 Bowl W/Drainer"},
            {code: "724", desc: "Sink, Scrub - Double Bay"},
            {code: "726", desc: "Sink, Work - 4 Station"},
            {code: "383", desc: "Skillet, Tilting"},
            {code: "1409", desc: "Slab, Ointment - Heated"},
            {code: "447", desc: "Speaker, Computer"},
            {code: "1410", desc: "Sphygmomanometer, Mercurial - Adult, Mobile"},
            {code: "1411", desc: "Sphygmomanometer, Paediatric - Boxed, Mercurial"},
            {code: "1412", desc: "Sphygmomanometer, Swivel Type - Wall Mounted"},
            {code: "1472", desc: "Spirometer"},
            {code: "1413", desc: "Stand, Basin - Single"},
            {code: "1414", desc: "Stand, Basin - Double"},
            {code: "1415", desc: "Stand, Basin - Large"},
            {code: "1463", desc: "Stand, Cerebral Palsy"},
            {code: "448", desc: "Stand, Computer"},
            {code: "654", desc: "Stadiometer"},
            {code: "239", desc: "Stand, Flowers"},
            {code: "1416", desc: "Stand, I.V. - Mobile"},
            {code: "380", desc: "Starter, Tray - W/Dish Lifter"},
            {code: "363", desc: "Station, Beverage"},
            {code: "236", desc: "Station, Executive Secretary"},
            {code: "1464", desc: "Steps"},
            {code: "727", desc: "Sterilizer, Counter Top"},
            {code: "728", desc: "Sterilizer, Vacuum - Double Door"},
            {code: "1500", desc: "Sticks, Exercise"},
            {code: "666", desc: "Stick, Walking - Adult Adjustable"},
            {code: "721", desc: "Still, Glass - Double Distillation"},
            {code: "1454", desc: "Stimulator, Ultrasonic"},
            {code: "1147", desc: "Stirrer - Direct Drive"},
            {code: "534", desc: "Stirrer, Magnetic"},
            {code: "1417", desc: "Stool, Anaesthetist's - W/Posture Back"},
            {code: "529", desc: "Stool - Auto Adjustable"},
            {code: "164", desc: "Stool, Bar - Fibre Glass"},
            {code: "1418", desc: "Stool, Examination - W/Back and Casters"},
            {code: "528", desc: "Stool, Lab - Mobile W/Back and Casters"},
            {code: "532", desc: "Stool, Revolving - Adjustable Height"},
            {code: "1502", desc: "Straps, Traction"},
            {code: "1419", desc: "Stretcher, Recovery"},
            {code: "1420", desc: "Stretcher, Transport - W/IV Pole"},
            {code: "392", desc: "Swyngomatic"},
            {code: "999", desc: "System, Paging"},
            {code: "277", desc: "System, Public Address"},
            {code: "000", desc: "System, Teleconference"},
            {code: "768", desc: "System, Tray Conveyor"},
            {code: "1421", desc: "System, X-ray - Radiographic"},
            {code: "1422", desc: "System, X-ray - Radiographic/Fluoroscopic"},
            {code: "1423", desc: "Table, Autopsy"},
            {code: "1424", desc: "Table, Autopsy - Dissecting Work"},
            {code: "1425", desc: "Table, Body viewing"},
            {code: "1426", desc: "Table, Delivery/OB"},
            {code: "1427", desc: "Table, Fracture - Portable"},
            {code: "1429", desc: "Table, Instrument"},
            {code: "1428", desc: "Table, Instrument - Dressing"},
            {code: "388", desc: "Table, Linen Inspection"},
            {code: "716", desc: "Table, Preparation and Packing"},
            {code: "201", desc: "Table, Single Legged"},
            {code: "1431", desc: "Table, Surgical - Manual, Minor"},
            {code: "1503", desc: "Table, Tilt"},
            {code: "1432", desc: "Table, Treatment - W/Storage"},
            {code: "1433", desc: "Table, Treatment - Physiotherapy"},
            {code: "685", desc: "Table, Work - Instrument Processing"},
            {code: "000", desc: "Tank, X-ray Chemical"},
            {code: "740", desc: "Thermometer"},
            {code: "1434", desc: "Timer, Interval - Alarmed"},
            {code: "1435", desc: "Tourniquet - Complete"},
            {code: "1504", desc: "Traction, cervical"},
            {code: "362", desc: "Transporter, Food - Mobile"},
            {code: "387", desc: "Tray, Serving"},
            {code: "1505", desc: "Treadmill"},
            {code: "394", desc: "Tripod, Video Camera"},
            {code: "1436", desc: "Trolley, Accident and Emergency - Patient"},
            {code: "1473", desc: "Trolley, Bath"},
            {code: "375", desc: "Trolley, Catering Cups"},
            {code: "378", desc: "Trolley, Catering Service"},
            {code: "1437", desc: "Trolley, Concealment"},
            {code: "777", desc: "Trolley, Cylinder"},
            {code: "1438", desc: "Trolley, Distribution - CSSD Collection"},
            {code: "1439", desc: "Trolley, Instrument - Small Dressing"},
            {code: "1440", desc: "Trolley, Instrument - Medium Dressing"},
            {code: "257", desc: "Trolley, Linen - Single"},
            {code: "1441", desc: "Trolley, Medicine - Basic W/Securing Device"},
            {code: "1442", desc: "Trolley, Mortuary"},
            {code: "1443", desc: "Trolley, Mortuary - Elevating 2 Tier W/Weighing"},
            {code: "778", desc: "Truck, Hand - Lightweight, Hi-Lift"},
            {code: "779", desc: "Truck, Platform"},
            {code: "1396", desc: "Regulator, Vacuum"},
            {code: "1461", desc: "Rollator"},
            {code: "1462", desc: "Rolls"},
            {code: "1508", desc: "Roller, Wrist"},
            {code: "258", desc: "Room, Chill"},
            {code: "259", desc: "Room, Cold"},
            {code: "1402", desc: "Safe, Drugs"},
            {code: "995", desc: "Saw, Meat"},
            {code: "1403", desc: "Scale, Autopsy"},
            {code: "1406", desc: "Scale, Blood Loss"},
            {code: "382", desc: "Scale, Hanging"},
            {code: "1407", desc: "Scale, Paediatric"},
            {code: "1408", desc: "Scale, Patient - W/Measuring Rod"},
            {code: "769", desc: "Scale, Platform - Floor Recessed"},
            {code: "381", desc: "Scale, Workshop - Dietary Ingredients"},
            {code: "418", desc: "Scanner"},
            {code: "764", desc: "Sealer, Heat - Cabinet Mounted - Electric"},
            {code: "369", desc: "Server, Cold Food"},
            {code: "368", desc: "Server, Hot Food"},
            {code: "686", desc: "Set, Pads - Foam Positioning"},
            {code: "533", desc: "Shaker, Carbon Dioxide"},
            {code: "385", desc: "Shelving, Single Side - Free Standing"},
            {code: "1497", desc: "Unit, Massage - Vibromaster"},
            {code: "1506", desc: "Vasotrain"},
            {code: "1509", desc: "Wardbox, Dispensary"},
            {code: "1001", desc: "Wardrobe"},
            {code: "1471", desc: "Warmer, Radiant"},
            {code: "1465", desc: "Wedge"},
            {code: "1507", desc: "Wheel, Shoulder"}
        ];

        window.ASSET_CODES_1997 = [
            {code: "695", desc: "Agilator"},
            {code: "149", desc: "Air Conditioner"},
            {code: "454", desc: "Amalgamator"},
            {code: "453", desc: "Analyser"},
            {code: "452", desc: "Analyser, Chloride"},
            {code: "451", desc: "Analyser, Blood Gas"},
            {code: "206", desc: "Ash Tray"},
            {code: "697", desc: "Aspirator"},
            {code: "698", desc: "Aspirator, Pipeline Mobile - H Vac Sgl Jar"},
            {code: "696", desc: "Auroscope"},
            {code: "450", desc: "Autoclave"},
            {code: "460", desc: "Bacti Cinerator"},
            {code: "463", desc: "Bank, Blood"},
            {code: "462", desc: "Baumanometer"},
            {code: "550", desc: "Bassinet"},
            {code: "224", desc: "Bath, Baby"},
            {code: "461", desc: "Bath, Flotation - Electric"},
            {code: "545", desc: "Bath, Water - Electric"},
            {code: "699", desc: "Bath, Wax"},
            {code: "758", desc: "Battery, Rechargeable"},
            {code: "557", desc: "Bed, Children's"},
            {code: "553", desc: "Bed, Circle"},
            {code: "457", desc: "Bed, Delivery"},
            {code: "110", desc: "Bed, Divan - Single"},
            {code: "111", desc: "Bed, Divan - Double"},
            {code: "556", desc: "Bed, Examination"},
            {code: "552", desc: "Bed, Hospital"},
            {code: "551", desc: "Bed, Obstetric/Labour"},
            {code: "554", desc: "Bed, Surgical/Operating"},
            {code: "555", desc: "Bed, Xray"},
            {code: "107", desc: "Bench, Plastic - With Back Rest"},
            {code: "105", desc: "Bench, Wooden - With Back Rest"},
            {code: "106", desc: "Bench, Wooden - Without Back Rest"},
            {code: "112", desc: "Bin, Dust - Plastic/Metal"},
            {code: "113", desc: "Bin, Step-on"},
            {code: "332", desc: "Bin, Storage - Plastic/Metal"},
            {code: "558", desc: "Bin, Linen"},
            {code: "226", desc: "Bicycle, Exercise"},
            {code: "464", desc: "Bitirisbinometer"},
            {code: "307", desc: "Blender"},
            {code: "901", desc: "Board, Drawing"},
            {code: "315", desc: "Board, Ironing"},
            {code: "185", desc: "Board, Notice"},
            {code: "100", desc: "Bookcase - Metal/Wooden"},
            {code: "104", desc: "Bookshelf"},
            {code: "753", desc: "Boiler"},
            {code: "754", desc: "Bucket - Plastic"},
            {code: "755", desc: "Bucket - Galvanized"},
            {code: "223", desc: "Buffet - Wooden/Glass"},
            {code: "465", desc: "Bunsen Burner"},
            {code: "115", desc: "Cabinet, Card - Single Drawer"},
            {code: "116", desc: "Cabinet, Card - Two (2) Drawer"},
            {code: "117", desc: "Cabinet, Card - Four (4) Drawer"},
            {code: "157", desc: "Cabinet, Card - Eight (8) Drawer"},
            {code: "129", desc: "Cabinet, Card - Eleven (11) Drawer"},
            {code: "122", desc: "Cabinet, Filing - Wooden"},
            {code: "121", desc: "Cabinet, Filing - Two (2) Drawer"},
            {code: "127", desc: "Cabinet, Filing - Three (3) Drawer"},
            {code: "119", desc: "Cabinet, Filing - Four (4) Drawer"},
            {code: "120", desc: "Cabinet, Filing - Five (5) Drawer"},
            {code: "125", desc: "Cabinet, Filing - Seven (7) Drawer"},
            {code: "118", desc: "Cabinet, Filing - Security - 4 Drawers"},
            {code: "126", desc: "Cabinet, Filing - Security - 2 Drawers"},
            {code: "128", desc: "Cabinet, Fireproof"},
            {code: "123", desc: "Cabinet, Chart"},
            {code: "466", desc: "Cabinet, Instrument"},
            {code: "159", desc: "Cabinet, Key - Metal/Wooden"},
            {code: "124", desc: "Cabinet, Liquor"},
            {code: "331", desc: "Cabinet, Household"},
            {code: "496", desc: "Cabinet, Laminar Flow"},
            {code: "565", desc: "Cabinet, Medicine"},
            {code: "704", desc: "Cabinet, Narcotic"},
            {code: "902", desc: "Cabinet, Storage"},
            {code: "404", desc: "Calculator"},
            {code: "701", desc: "Calscope"},
            {code: "806", desc: "Camera, Dark Room"},
            {code: "470", desc: "Camera, Xray"},
            {code: "660", desc: "Cart, Emergency Crash"},
            {code: "662", desc: "Cart, Medication"},
            {code: "659", desc: "Cart, Oxygen With Regulator"},
            {code: "403", desc: "Cash Pan"},
            {code: "401", desc: "Cash Register"},
            {code: "566", desc: "Cassette, Film - X-ray"},
            {code: "576", desc: "Cavitron"},
            {code: "471", desc: "Centrifuge"},
            {code: "481", desc: "Centre, Embedding"},
            {code: "131", desc: "Chair, Bucket"},
            {code: "147", desc: "Chair, Artist - Swivel"},
            {code: "143", desc: "Chair, Antique - Wooden"},
            {code: "133", desc: "Chair, Executive - Metal/Upholstered"},
            {code: "130", desc: "Chair, Conference"},
            {code: "145", desc: "Chair, Danish"},
            {code: "559", desc: "Chair, Dental"},
            {code: "141", desc: "Chair, Patio"},
            {code: "139", desc: "Chair, Plastic"},
            {code: "136", desc: "Chair, Metal With Wood"},
            {code: "168", desc: "Chair, Lecture - Metal With Wood"},
            {code: "152", desc: "Chair, Lounge"},
            {code: "197", desc: "Chair, Settee"},
            {code: "138", desc: "Chair, Straight - Metal"},
            {code: "140", desc: "Chair, Straight - Wooden"},
            {code: "137", desc: "Chair, Straight - Upholstered/Metal"},
            {code: "135", desc: "Chair, Upholstered/Metal With Arm"},
            {code: "142", desc: "Chair, Swivel - Wooden With Arm"},
            {code: "134", desc: "Chair, Typist"},
            {code: "146", desc: "Chair, Wheel"},
            {code: "169", desc: "Chalk Board"},
            {code: "408", desc: "Charger, Radio"},
            {code: "406", desc: "Cheque Singer"},
            {code: "222", desc: "Chest of Drawers"},
            {code: "852", desc: "Clamp, Vice"},
            {code: "321", desc: "Cleaner, Vacuum"},
            {code: "155", desc: "Clock, Electric/Battery"},
            {code: "702", desc: "Clock, Elapsed Time - With Control and Reset"},
            {code: "759", desc: "Compressor, Air"},
            {code: "757", desc: "Compressor Unit"},
            {code: "405", desc: "Computer Terminal"},
            {code: "564", desc: "Conditioner, Glove"},
            {code: "563", desc: "Controller, Infusion"},
            {code: "562", desc: "Controller, X-ray"},
            {code: "338", desc: "Cooker, Pressure"},
            {code: "337", desc: "Cooler, Electric"},
            {code: "148", desc: "Cooler, Water"},
            {code: "414", desc: "Copier, Photo"},
            {code: "416", desc: "Copier, Photo - Special"},
            {code: "427", desc: "Copier, Stencil"},
            {code: "221", desc: "Cot, Children's"},
            {code: "561", desc: "Couch, Examination"},
            {code: "132", desc: "Couch, Upholstered"},
            {code: "227", desc: "Couch, Treatment - Plinth"},
            {code: "427", desc: "Counter"},
            {code: "700", desc: "Counter, Blood Cell - Electric"},
            {code: "153", desc: "Cupboard, Glass"},
            {code: "156", desc: "Cupboard, Linen"},
            {code: "150", desc: "Cupboard, Metal"},
            {code: "151", desc: "Cupboard, Wooden"},
            {code: "429", desc: "Cutter, Paper (Guillotine)"},
            {code: "808", desc: "Cutter, Paper"},
            {code: "579", desc: "Cutter, Cast"},
            {code: "341", desc: "Cutter, Meat"},
            {code: "881", desc: "Cutter, Side"},
            {code: "467", desc: "Cyrostact"},
            {code: "325", desc: "Cylinder, Gas"},
            {code: "326", desc: "Cylinder, Oxygen"},
            {code: "327", desc: "Cylinder, Nitrous Oxide"},
            {code: "468", desc: "Cytospin - Electric"},
            {code: "560", desc: "Crib"},
            {code: "569", desc: "Crutch, Arm - Adult"},
            {code: "568", desc: "Crutch, Arm - Child"},
            {code: "423", desc: "Datashield"},
            {code: "410", desc: "Data Processing Auto Equipment"},
            {code: "613", desc: "Defibrillator Monitor"},
            {code: "474", desc: "Dessicator"},
            {code: "167", desc: "Desk, Class Room"},
            {code: "162", desc: "Desk, Executive - Wooden/Metal"},
            {code: "160", desc: "Desk, Single - Wooden/Metal"},
            {code: "165", desc: "Desk, Typist - Junior Wooden/Metal"},
            {code: "166", desc: "Desk, Typist - Senior, Metal"},
            {code: "708", desc: "Densimeter"},
            {code: "707", desc: "Diaphanoscope"},
            {code: "573", desc: "Dilator, Uterine"},
            {code: "478", desc: "Diluter"},
            {code: "705", desc: "Dinamap"},
            {code: "330", desc: "Dining Set - Wooden"},
            {code: "170", desc: "Dip, Standing - Wooden"},
            {code: "171", desc: "Dip, Table - Wooden"},
            {code: "706", desc: "Dish, Kidney"},
            {code: "477", desc: "Dispenser, Dilator - Electric"},
            {code: "475", desc: "Distiller, Water"},
            {code: "347", desc: "Dispenser, Sanitizer"},
            {code: "572", desc: "Docket case - Wooden"},
            {code: "804", desc: "Drill, paper"},
            {code: "570", desc: "Drum, Dressing"},
            {code: "571", desc: "Dryer, Film - X-ray"},
            {code: "328", desc: "Dryer, Hair"},
            {code: "329", desc: "Dryer, Hand - Electric"},
            {code: "479", desc: "Dryer, Slide"},
            {code: "476", desc: "Dynaclave"},
            {code: "290", desc: "Easel"},
            {code: "621", desc: "Erogometer"},
            {code: "576", desc: "Extinguisher, Fire"},
            {code: "574", desc: "Extractor"},
            {code: "176", desc: "Fan, Box - Electric"},
            {code: "174", desc: "Fan, Electric 12\""},
            {code: "175", desc: "Fan, Desk/Standing - Electric"},
            {code: "575", desc: "Fan, Heater - X-ray"},
            {code: "177", desc: "Fan, Ceiling"},
            {code: "480", desc: "Fibrometer"},
            {code: "411", desc: "Films"},
            {code: "239", desc: "Flashlight"},
            {code: "801", desc: "Folder, Mechanical"},
            {code: "578", desc: "Forceps"},
            {code: "850", desc: "Fork, Agricultural"},
            {code: "310", desc: "Freezer, Deep"},
            {code: "577", desc: "Fridge, Blood"},
            {code: "306", desc: "Fryer, Deep - Gas/Electric"},
            {code: "858", desc: "Funnel - Enamel/Metal"},
            {code: "859", desc: "Funnel - Gas"},
            {code: "580", desc: "Gallipot"},
            {code: "756", desc: "Generator"},
            {code: "240", desc: "Glass, Measuring"},
            {code: "486", desc: "Healing Block"},
            {code: "186", desc: "Heater, Water"},
            {code: "485", desc: "Haemoglobinmeter"},
            {code: "860", desc: "Hammer, Ball Pein"},
            {code: "903", desc: "Hamper, Linen"},
            {code: "228", desc: "Hassock"},
            {code: "583", desc: "Holder, Cassette"},
            {code: "582", desc: "Holder, Film X-ray"},
            {code: "581", desc: "Holder, Swab"},
            {code: "484", desc: "Holder, Test Tube"},
            {code: "853", desc: "Hose, Garden"},
            {code: "305", desc: "Hot Plate"},
            {code: "335", desc: "Icebox"},
            {code: "336", desc: "Ice Maker"},
            {code: "322", desc: "Igloo"},
            {code: "591", desc: "Illuminator, X-ray"},
            {code: "589", desc: "Incinerator"},
            {code: "590", desc: "Incubator"},
            {code: "487", desc: "Inspissator"},
            {code: "488", desc: "Ioniser"},
            {code: "317", desc: "Iron, Clothes - Electric"},
            {code: "334", desc: "Ironer, Flat Work (Clothes Iron)"},
            {code: "333", desc: "Juicer"},
            {code: "309", desc: "Kettle, Electric"},
            {code: "865", desc: "Knife, Swivel"},
            {code: "750", desc: "Ladder - Metal"},
            {code: "751", desc: "Ladder - Wooden"},
            {code: "270", desc: "Lamp, Bedside"},
            {code: "595", desc: "Lamp, Dental"},
            {code: "272", desc: "Lamp, Desk"},
            {code: "273", desc: "Lamp, Emergency - Fluorescent"},
            {code: "597", desc: "Lamp, Heat"},
            {code: "274", desc: "Lamp, Kerosene (Oil)"},
            {code: "592", desc: "Lamp, Halogen"},
            {code: "593", desc: "Lamp, Infra - Red"},
            {code: "598", desc: "Lamp, Operating"},
            {code: "596", desc: "Lamp, Examination - Standing"},
            {code: "271", desc: "Lamp, Spirit"},
            {code: "594", desc: "Lamp, Ultra Violet"},
            {code: "390", desc: "Lantern, Oil"},
            {code: "715", desc: "Laryngoscope"},
            {code: "289", desc: "Lectern"},
            {code: "866", desc: "Level, Spirit"},
            {code: "776", desc: "Lifter, Pallet"},
            {code: "599", desc: "Light, Examination - Ceiling Mounted"},
            {code: "495", desc: "Light Unit, Dark Room"},
            {code: "182", desc: "Locker, Bedside - Metal/Wooden"},
            {code: "180", desc: "Locker, Metal"},
            {code: "181", desc: "Locker, Wooden"},
            {code: "183", desc: "Locker, Multi-tier 5 Compartment"},
            {code: "400", desc: "Machine, Accounting"},
            {code: "402", desc: "Machine, Adding"},
            {code: "600", desc: "Machine, Anaesthetic"},
            {code: "601", desc: "Machine, Asthmatic"},
            {code: "602", desc: "Machine, Autocrit PCV"},
            {code: "609", desc: "Machine, Automatic Film Processor (X-ray)"},
            {code: "431", desc: "Machine, Binding - Electric"},
            {code: "500", desc: "Machine, Blood Pressure - Portable"},
            {code: "501", desc: "Machine, Blood Test"},
            {code: "603", desc: "Machine, Cardiac ECG"},
            {code: "604", desc: "Machine, Diathermy"},
            {code: "412", desc: "Machine, Duplicating"},
            {code: "311", desc: "Machine, Drying - Clothes"},
            {code: "612", desc: "Machine, ECG with Defibrillator"},
            {code: "605", desc: "Machine, Electrosectilis"},
            {code: "503", desc: "Machine, Electrolite"},
            {code: "610", desc: "Machine, Fogging"},
            {code: "430", desc: "Machine, Fax"},
            {code: "606", desc: "Machine, Kleet"},
            {code: "432", desc: "Machine, Numbering"},
            {code: "611", desc: "Machine, Pulmo Aide"},
            {code: "313", desc: "Machine, Sewing - Electric"},
            {code: "434", desc: "Machine, Shredding"},
            {code: "527", desc: "Machine, Slide Staining"},
            {code: "607", desc: "Machine, Slow Piece"},
            {code: "608", desc: "Machine, Suction"},
            {code: "436", desc: "Machine, Transparency"},
            {code: "616", desc: "Machine, Ultra Sound"},
            {code: "314", desc: "Machine, Washing - Clothes"},
            {code: "312", desc: "Machine, Wringer"},
            {code: "717", desc: "Magnet, Eye - Hand Held"},
            {code: "626", desc: "Marker, Actinic - X-ray"},
            {code: "188", desc: "Mattress"},
            {code: "280", desc: "Megaphone"},
            {code: "505", desc: "Meter, PH"},
            {code: "731", desc: "Meter, Pulse (Oximeter)"},
            {code: "433", desc: "Microfishe"},
            {code: "509", desc: "Microplate"},
            {code: "508", desc: "Microscope"},
            {code: "511", desc: "Microtome"},
            {code: "184", desc: "Mirror (Standing)"},
            {code: "308", desc: "Mixer, Food - Electric"},
            {code: "507", desc: "Mixer, Blood"},
            {code: "506", desc: "Mixer, Medicine"},
            {code: "619", desc: "Monitor, Cardiac - Electric"},
            {code: "618", desc: "Monitor, Foetal"},
            {code: "760", desc: "Mop Pan"},
            {code: "851", desc: "Mower, Lawn"},
            {code: "620", desc: "Nebulizer"},
            {code: "725", desc: "Ophthalmoscope"},
            {code: "319", desc: "Oven, Electric"},
            {code: "339", desc: "Oven, Gas"},
            {code: "510", desc: "Oven, Hot Air"},
            {code: "187", desc: "Oven, Microwave"},
            {code: "731", desc: "Oximeter - (Pulse Meter)"},
            {code: "730", desc: "Pan, Bed"},
            {code: "318", desc: "Pan, Washing"},
            {code: "519", desc: "Paraffin Block Drawers - Plastic"},
            {code: "340", desc: "Peeler, Potato"},
            {code: "800", desc: "Perforator"},
            {code: "320", desc: "Percolator - Electric"},
            {code: "622", desc: "Photometer, Flame"},
            {code: "623", desc: "Photometer, Spectro"},
            {code: "294", desc: "Piano"},
            {code: "520", desc: "Pitcher, Paraffin"},
            {code: "803", desc: "Platemaker"},
            {code: "220", desc: "Playpen"},
            {code: "870", desc: "Pliers, Bind Beak"},
            {code: "871", desc: "Pliers, Channel Lock"},
            {code: "872", desc: "Pliers, Combination"},
            {code: "316", desc: "Polisher, Electric"},
            {code: "624", desc: "Porringer"},
            {code: "762", desc: "Power Supply"},
            {code: "345", desc: "Pot, Steam"},
            {code: "802", desc: "Press, Printing"},
            {code: "225", desc: "Press, Wooden"},
            {code: "407", desc: "Printer"},
            {code: "437", desc: "Printer, Laser"},
            {code: "428", desc: "Printer, Stencil"},
            {code: "438", desc: "Printer, Cheque"},
            {code: "625", desc: "Processor"},
            {code: "344", desc: "Processor, Food"},
            {code: "291", desc: "Projector"},
            {code: "282", desc: "Projector, Film 20 MM"},
            {code: "283", desc: "Projector, Overhead"},
            {code: "284", desc: "Projector, Slide"},
            {code: "281", desc: "Projector, Film 16 MM"},
            {code: "761", desc: "Projector, Surge"},
            {code: "901", desc: "Pump"},
            {code: "873", desc: "Punch, Masonary"},
            {code: "413", desc: "Punch, 3 Hole"},
            {code: "630", desc: "Rack, Filing - Metal"},
            {code: "522", desc: "Rack, Chart"},
            {code: "631", desc: "Rack, Swab Count"},
            {code: "521", desc: "Rack, X-ray"},
            {code: "518", desc: "Rack, Staining - Metal"},
            {code: "297", desc: "Radio, Communication - Portable"},
            {code: "278", desc: "Radio, Communication - Mobile"},
            {code: "861", desc: "Rake, Agricultural"},
            {code: "298", desc: "Recorder, Tape"},
            {code: "279", desc: "Recorder, Tape - Reel to Reel"},
            {code: "288", desc: "Recorder, Video Cassette"},
            {code: "193", desc: "Refrigerator, 5-8 Cuft."},
            {code: "192", desc: "Refrigerator, 9/10 Cuft."},
            {code: "190", desc: "Refrigerator, 12 Cuft."},
            {code: "191", desc: "Refrigerator, 15 Cuft."},
            {code: "194", desc: "Refrigerator, 20 Cuft."},
            {code: "189", desc: "Refrigerator, Under Counter 3-6 Cuft."},
            {code: "763", desc: "Regulator, Current"},
            {code: "632", desc: "Respirator"},
            {code: "633", desc: "Resuscitator"},
            {code: "629", desc: "Rotator"},
            {code: "523", desc: "Rotator, Clinical"},
            {code: "647", desc: "Scale, Adult - Standing"},
            {code: "645", desc: "Scale, Baby"},
            {code: "658", desc: "Scale, Heavy Duty"},
            {code: "648", desc: "Scale, Table - Hanging/Counter"},
            {code: "653", desc: "Scale - weight Balanced"},
            {code: "875", desc: "Saw, Hack"},
            {code: "876", desc: "Saw, Tennon"},
            {code: "857", desc: "Scoop - Metal"},
            {code: "649", desc: "Screen, Bed"},
            {code: "287", desc: "Screen, Film"},
            {code: "652", desc: "Screen, X-ray View"},
            {code: "644", desc: "Screen, Lead"},
            {code: "733", desc: "Screen, Projector"},
            {code: "877", desc: "Screwdriver, Flat Point"},
            {code: "787", desc: "Screwdriver, Phillips"},
            {code: "736", desc: "Scissors"},
            {code: "435", desc: "Seal, Authenticity"},
            {code: "764", desc: "Sealer, Electric"},
            {code: "526", desc: "Serofuge"},
            {code: "744", desc: "Set, Auricular"},
            {code: "732", desc: "Set, Diagnostic"},
            {code: "734", desc: "Set, Post Mortem"},
            {code: "880", desc: "Set, Socket"},
            {code: "879", desc: "Set, Spanner"},
            {code: "743", desc: "Set, Surgical Instrument"},
            {code: "196", desc: "Settee - Danish"},
            {code: "197", desc: "Settee - Assorted"},
            {code: "524", desc: "Shaker, Specimen"},
            {code: "409", desc: "Sharpener, Pencil"},
            {code: "415", desc: "Sharpener, Pencil - Electric"},
            {code: "353", desc: "Sharpener, Knife - Electric"},
            {code: "354", desc: "Sharpener, Knife - Manual"},
            {code: "854", desc: "Shear, Hedge"},
            {code: "219", desc: "Shelf, on Wheels"},
            {code: "215", desc: "Shelf, Medical Records - Wooden with Doors"},
            {code: "216", desc: "Shelf, Medical Records - Wooden Without Doors"},
            {code: "217", desc: "Shelf, Medical Records - Metal with Doors"},
            {code: "218", desc: "Shelf, Medical Records - Metal without Doors"},
            {code: "855", desc: "Shovel"},
            {code: "881", desc: "Side Cutter"},
            {code: "738", desc: "Skeleton"},
            {code: "651", desc: "Sonalator, Medco"},
            {code: "767", desc: "Stabilizer"},
            {code: "636", desc: "Stand, Bed"},
            {code: "643", desc: "Stand, Foot"},
            {code: "639", desc: "Stand, Mayo"},
            {code: "640", desc: "Stand, Saline (Drip)"},
            {code: "745", desc: "Stand, Infusion"},
            {code: "205", desc: "Stand, Telephone"},
            {code: "195", desc: "Stand, Television"},
            {code: "235", desc: "Stand, Wooden/Metal"},
            {code: "296", desc: "Stapler, Electric"},
            {code: "299", desc: "Stapler, Heavy Duty/Staple Gun"},
            {code: "295", desc: "Stapler, Strong Arm"},
            {code: "646", desc: "Steamer"},
            {code: "525", desc: "Sterilizer"},
            {code: "737", desc: "Stethoscope"},
            {code: "642", desc: "Stethoscope, Foetal"},
            {code: "540", desc: "Still, Steam"},
            {code: "807", desc: "Stitcher, Wire"},
            {code: "856", desc: "Stone, Grind"},
            {code: "198", desc: "Stool - Wooden"},
            {code: "199", desc: "Stool - Metal"},
            {code: "200", desc: "Stool - Upholstered with Back Rest"},
            {code: "650", desc: "Stool, Foot"},
            {code: "301", desc: "Stove, Electric - Two (2) Burner"},
            {code: "356", desc: "Stove, Electric - Three (3) Burner"},
            {code: "352", desc: "Stove, Electric - Four (4) Burner"},
            {code: "355", desc: "Stove, Electric - Six (6) Burner"},
            {code: "300", desc: "Stove, Gas - Two (2) Burner"},
            {code: "302", desc: "Stove, Gas - Three (3) Burner"},
            {code: "304", desc: "Stove, Gas - Four (4) Burner"},
            {code: "323", desc: "Stove, Gas - Six (6) Burner"},
            {code: "324", desc: "Stove, Gas - Ten (10) Burner"},
            {code: "350", desc: "Stove, Kerosene - One (1) Burner"},
            {code: "351", desc: "Stove, Kerosene - Two (2) Burner"},
            {code: "735", desc: "Speculum"},
            {code: "654", desc: "Sphygnomanometer"},
            {code: "656", desc: "Sphygnomanometer, Mercurial - Wall Mounted"},
            {code: "342", desc: "Strainer - Metal"},
            {code: "641", desc: "Stretcher"},
            {code: "747", desc: "Stretcher, Transport - W/IV Pole/Side Rails"},
            {code: "202", desc: "Suite, Danish - Two (2) Chairs and One Settee"},
            {code: "203", desc: "Suite, Living Room - Five (5) Pieces"},
            {code: "761", desc: "Surge Protector"},
            {code: "742", desc: "Syringe"},
            {code: "739", desc: "Syringe, Ear"},
            {code: "664", desc: "Table, Anaesthetic"},
            {code: "212", desc: "Table, Bedside/Night"},
            {code: "207", desc: "Table, Coffee"},
            {code: "210", desc: "Table, Conference - Folding Table"},
            {code: "233", desc: "Table, Drawing"},
            {code: "232", desc: "Table, Examination"},
            {code: "211", desc: "Table, Formica"},
            {code: "805", desc: "Table, Light"},
            {code: "231", desc: "Table, Metal"},
            {code: "665", desc: "Table, Operating"},
            {code: "671", desc: "Table, Overbed"},
            {code: "230", desc: "Table, Packing - Wooden"},
            {code: "214", desc: "Table, Patio"},
            {code: "285", desc: "Table, Projector"},
            {code: "208", desc: "Table - Wooden"},
            {code: "669", desc: "Table, X-ray"},
            {code: "765", desc: "Tank, Storage"},
            {code: "292", desc: "Television"},
            {code: "741", desc: "Tenoculum, Uterine"},
            {code: "538", desc: "Tent, Aerosol/Mist"},
            {code: "526", desc: "Tent, Canvas"},
            {code: "539", desc: "Tent, Oxygen"},
            {code: "348", desc: "Thermos"},
            {code: "343", desc: "Toaster - Electric"},
            {code: "628", desc: "Torniquet, Pneumatic"},
            {code: "766", desc: "Transformer"},
            {code: "172", desc: "Tray, Document - Plastic"},
            {code: "173", desc: "Tray, Document - Wire/Wooden"},
            {code: "530", desc: "Tray, Film Developing"},
            {code: "673", desc: "Tray, Instrument"},
            {code: "286", desc: "Tripod"},
            {code: "114", desc: "Trolley, Card"},
            {code: "663", desc: "Trolley, Dressing"},
            {code: "661", desc: "Trolley, Food"},
            {code: "655", desc: "Trolley, General"},
            {code: "657", desc: "Trolley, Instrument"},
            {code: "531", desc: "Trolley, Laboratory"},
            {code: "672", desc: "Trolley, Linen"},
            {code: "662", desc: "Trolley, Medicine/Drug"},
            {code: "775", desc: "Trolley, Truck (Hand Truck)"},
            {code: "885", desc: "Trowel, Masonary"},
            {code: "670", desc: "Tube Head, X-ray"},
            {code: "420", desc: "Typewriter - Electric 18\""},
            {code: "417", desc: "Typewriter - Electric 19\""},
            {code: "425", desc: "Typewriter - Manual"},
            {code: "426", desc: "Typewriter - Memory Writer"},
            {code: "424", desc: "Typewriter - Word Processor"},
            {code: "422", desc: "Typewriter - Wheelwriter"},
            {code: "674", desc: "Unit, Breathing Therapy"},
            {code: "676", desc: "Unit, Electro Surgical"},
            {code: "675", desc: "Unit, Filing"},
            {code: "677", desc: "Unit, Intensive Care"},
            {code: "617", desc: "Unit, Manual Processing - X-ray"},
            {code: "544", desc: "Unit, X-ray"},
            {code: "690", desc: "Unit, X-ray - Dental"},
            {code: "543", desc: "Unit, X-ray - Portable"},
            {code: "213", desc: "Vanity (Dresser) - Wooden"},
            {code: "398", desc: "Vault"},
            {code: "680", desc: "Ventilator"},
            {code: "681", desc: "Vibrator, Precussion/Mechanical"},
            {code: "541", desc: "Viewer, Agglutination"},
            {code: "542", desc: "View Box, X-ray"},
            {code: "682", desc: "Vitalograph"},
            {code: "687", desc: "Walker, Help - Metal"},
            {code: "391", desc: "Warmer, Food"},
            {code: "748", desc: "Warmer, Blood"},
            {code: "318", desc: "Wash Pan"},
            {code: "346", desc: "Washer, Dish"},
            {code: "545", desc: "Water Bath - Electric"},
            {code: "749", desc: "Wheel Barrow"},
            {code: "752", desc: "Work Bench - Wooden"},
            {code: "234", desc: "Work Station"},
            {code: "890", desc: "Wrench, Pipe"},
            {code: "770", desc: "Wringer, Extractor - Electric"},
            {code: "399", desc: "Wringer, Mop"}
        ];

// Merge the base register with any custom codes the admin added (localStorage).
window.getAssetCodesShared = function (year) {
    var custom = [];
    try { custom = JSON.parse(localStorage.getItem("assetDashboardCustomCodes") || "[]"); } catch (e) {}
    if (year === "new") {
        return custom.filter(function (c) { return c.year === "new"; })
            .map(function (i) { return { code: i.code, desc: i.desc, custom: true, id: i.id }; });
    }
    var base = year === "1998" ? window.ASSET_CODES_1998 : window.ASSET_CODES_1997;
    var cu = custom.filter(function (c) { return c.year === year; })
        .map(function (i) { return { code: i.code, desc: i.desc, custom: true, id: i.id }; });
    return base.map(function (i) { return { code: i.code, desc: i.desc, custom: false }; }).concat(cu);
};
